name: ShadeBox
description: "shadebox"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  media_kit: ^1.1.11
  media_kit_video: ^1.1.5
  media_kit_libs_windows_video: ^1.0.10
  media_kit_libs_linux: ^1.1.3
  http: ^1.1.0
  html: ^0.15.4
  file_picker: ^9.0.1
  dio: ^5.8.0+1
  shared_preferences: ^2.5.2
  flex_color_scheme: ^8.1.1
  google_fonts: ^6.2.1
  hugeicons: ^0.0.7
  window_manager: ^0.4.3
  video_player: ^2.9.3
  flex_color_picker: ^3.7.0
  path_provider: ^2.0.15
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  process_run: ^1.2.3
  archive: ^4.0.3
  encrypt: ^5.0.3

flutter_launcher_icons:
  image_path: "assets/app_icon.png"
  windows:
    generate: true
    image_path: "assets/app_icon.png"
  linux:
    generate: true
    image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
